name: wishlist-local

services:
  db:
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker

  mail:
    ports:
      - "1080:1080"
      - "1025:1025"

  valkey:
    ports:
      - "6381:6379"

volumes:
  postgres_data:
